pipelines:
  - name: jira_transition_task_publish_pipeline
    configuration:
      jfrogCliVersion: 2
      integrations:
        - name: hk_jiraIntegration
    steps:
      - name: jira_task_demo
        type: Bash
        execution:
          onExecute:
            - exit 1
          onFailure:
            # Run JIRA Comment task
            - task: jfrog/jira-comment@v0.1.0
              input:
                issueKey: "PIPE-13213"
                jiraIntegrationName: "hk_jiraIntegration"
                comment: "Commenting ${run_number}"
            # Run JIRA Transition task
            - task: jfrog/jira-transition@v0.0.1
              input:
                issueKey: "PIPE-13213"
                jiraIntegrationName: "hk_jiraIntegration"
                transitionName: "In Progress"