resources:
  - name: jfrog_pipeline_repo
    type: GitRepo
    configuration:
      path: harshkumar1/jfrog-pipelines
      gitProvider: hk_github_sample
      branches:
        include: ^main$
      cloneProtocol: https

pipelines:
  - name: s3upload_task_demo_pipeline
    configuration:
      integrations:
        - name: hk_awsIntegration
        - name: hk_artifactory
      inputResources:
        - name: jfrog_pipeline_repo
          trigger: false
      environmentVariables:
        readOnly:
          env1: read_only_env1
          env2:
            default: env2_pipe_value2
            description: This is env2 description
            values:
              - env2_pipe_value1
              - env2_pipe_value2
              - env2_pipe_value3
          env3:
              default: env3_pipe_value3
              description: This is step_env1 description
              values:
                - env3_pipe_value1
                - env3_pipe_value2
                - env3_pipe_value3
              allowCustom: true
    steps:
      - name: s3upload_task_demo
        type: Bash
        configuration:
          environmentVariables:
            step_env1: step_env1
            step_env2:
              default: step_env2_value1
              description: This is env2 description
              values:
                - step_env2_value1
                - step_env2_value2
                - step_env2_value3
            step_env3:
              default: step_env3_value3
              description: This is step_env1 description
              values:
                - step_env3_value1
                - step_env3_value2
                - step_env3_value3
              allowCustom: true
        execution:
          onExecute:
            - echo "onExecute"
            - echo ${env1}
            - echo ${env2}
            - echo ${env3}
            - echo ${step_env1}
            - echo ${step_env2}
            - echo ${step_env3}
          onComplete:
            # S3 Upload Task
            - task: jfrog/upload-file-to-s3@v0.1.0
              input:
                sourceFilePath: "${res_jfrog_pipeline_repo_resourcePath}/sample.txt"
                targetBucketName: "harsh-s3-bucket-1"
                awsIntegration: "hk_awsIntegration"